config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/userpersnaldet.rb
class Userpersnaldet < ApplicationRecord
  belongs_to :user
end

app/controllers/userpersnaldets_controller.rb
class UserpersnaldetsController < ApplicationController
  before_action :set_userpersnaldet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil
      redirect_to new_reg_path

    end
  end
  # GET /userpersnaldets
  # GET /userpersnaldets.json
  def index
    @userpersnaldets = Userpersnaldet.all
    if user_signed_in?
      @det = Userpersnaldet.all
      @dets = @det.find(current_user.id)
    end

  end

  # GET /userpersnaldets/1
  # GET /userpersnaldets/1.json
  def show
    redirect_to programs_path
  end

  # GET /userpersnaldets/new
  def new
    @userpersnaldet = Userpersnaldet.new
  end

  # GET /userpersnaldets/1/edit
  def edit
  end

  # POST /userpersnaldets
  # POST /userpersnaldets.json
  def create
    @userpersnaldet = Userpersnaldet.new(userpersnaldet_params)

    respond_to do |format|
      if @userpersnaldet.save
        format.html { redirect_to @userpersnaldet, notice: 'Your personal data was successfully created.' }
        format.json { render :show, status: :created, location: @userpersnaldet }
      else
        format.html { render :new }
        format.json { render json: @userpersnaldet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userpersnaldets/1
  # PATCH/PUT /userpersnaldets/1.json
  def update
    respond_to do |format|
      if @userpersnaldet.update(userpersnaldet_params)
        format.html { redirect_to @userpersnaldet, notice: 'Your personal data was successfully updated.' }
        format.json { render :show, status: :ok, location: @userpersnaldet }
      else
        format.html { render :edit }
        format.json { render json: @userpersnaldet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userpersnaldets/1
  # DELETE /userpersnaldets/1.json
  def destroy
    @userpersnaldet.destroy
    respond_to do |format|
      format.html { redirect_to userpersnaldets_url, notice: 'Your personal data was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userpersnaldet
      @userpersnaldet = Userpersnaldet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userpersnaldet_params
      params.require(:userpersnaldet).permit(:Name, :Age ,:gender,:Contact_Number, :Address, :About_MAC,:gender)
    end
end

app/helpers/userpersnaldets_helper.rb
module UserpersnaldetsHelper
	def username
		@username = Userpersnaldet.all
      	@username = @username.find(current_user.id)
      	@username = @username.Name
	end
end

app/views/userpersnaldets/_form.html.erb
<%= form_for(userpersnaldet) do |f| %>
  <% if userpersnaldet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userpersnaldet.errors.count, "error") %> prohibited this userpersnaldet from being saved:</h2>

      <ul>
      <% userpersnaldet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Age %>
    <%= f.number_field :Age %>
  </div>
  <div class="field">
   <table><tr>
   <td colspan="1cm" style="width: 1cm"><%= f.label :Male %></td><td colspan="1cm" style="width: 1cm"><%= f.radio_button :gender ,:true, {:checked => true} %></td>
   <td style="width: 1.5cm"><%= f.label :Female %></td><td ><%= f.radio_button :gender ,:false%></td>
   </tr> </table>
  </div>
  <div class="field">
    <%= f.label :Contact_Number %>
    <%= f.text_field :Contact_Number %>
  </div>

  <div class="field">
    <%= f.label :Address %>
    <%= f.text_area :Address %>
  </div>

  <div class="field">
    <%= f.label :About_MAC %>
    <%= f.text_area :About_MAC %>
  </div>

  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>
<%= button_to 'Skip', programs_path,method: :get %>

app/views/userpersnaldets/edit.html.erb
<h1>Editing Userpersnaldet</h1>

<%= render 'form', userpersnaldet: @userpersnaldet %>

<%= link_to 'Show', @userpersnaldet %> |
<%= link_to 'Back', userpersnaldets_path %>

app/views/userpersnaldets/index.html.erb
<style>
  th {
  padding: 12px;
  border: 3px solid black;
background: green;
color: white;
font-weight: bold;
}
td#id{
padding: 12px;
border: 3px solid black;
text-align: left;
  background: #eee;
}
</style>


<p id="notice"><%= notice %></p>
<% if user_signed_in? && !username.nil?  %>
<h3><%=username %> personal details</h3>
    <% else if user_signed_in? && username.nil?%>
    <h3><%= current_user.email %> personl details</h3><% end %><% end %><br>

<% if user_signed_in? %>
<table  align="center">

  <thead>

    <tr align="center">
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Contact number</th>
      <th>Address</th>
      <th>About mac</th>
    </tr>
  </thead>

  <tbody>


      <tr align="center">

        <td id="id"><%= @dets.Name %></td>
        <td id="id"><%= @dets.Age %></td>
        <td id="id"><%if @dets.gender == true %>
              <%="Male"%>
              <%elsif @dets.gender == false%>
              <%="Female"%>
          <%elsif @dets.gender == nil?%>
          <%end%></td>
        <td id="id"><%= @dets.Contact_Number %></td>
        <td id="id"><%= @dets.Address %></td>
        <td id="id"><%= @dets.About_MAC %></td>
      </tr>
  </tbody>

  <tr>

  <td ><br><%= button_to 'Edit', edit_userpersnaldet_path(@dets.id),method: :get , :class=>"btn btn-primary btn-sm btn-block"%></td>
  <td ><br><%= button_to 'Skip', programs_path,method: :get , :class=>"btn btn-default btn-sm btn-block"%></td></tr>
</table>

<% end %>
<br>

app/views/userpersnaldets/new.html.erb
<% if @userpersnaldets.nil?  %>

    <script type="text/javascript">
      window.location.href="/programs"  // put your correct path in a string here
    </script>
<% else %>
    <h1 align="center">Personal Details</h1>

    <%= render 'form', userpersnaldet: @userpersnaldet %>

<%= link_to 'Back', userpersnaldets_path %>

<% end %>

app/views/userpersnaldets/show.html.erb
<p id="notice"><%= notice %></p>
<table>

  <p>
  <strong>Name:</strong>
  <%=  @userpersnaldet.Name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @userpersnaldet.Age %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @userpersnaldet.Contact_Number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @userpersnaldet.Address %>
</p>

<p>
  <strong>About mac:</strong>
  <%= @userpersnaldet.About_MAC %>
</p>

<%= link_to 'Edit', edit_userpersnaldet_path(@userpersnaldet), :class=>"btn btn-info" %> |
<%= link_to 'Back', userpersnaldets_path %>
</table>