config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  validates :Event_Name,:event_details, presence: true
  mount_uploader :file_name, MediaUploader
  has_many :comts
  belongs_to :user
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil
      redirect_to new_reg_path

    end
  end
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
    #@zap = current_user.id
    #@success = CardTransaction.find(1)
  end


  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @user= current_user
    @program = @user.programs.new(program_params)

    respond_to do |format|
      if @program.save
        ProgramMailer.program_created(current_user,@program.Event_Name).deliver
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_program
    @program = Program.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:Event_Name,:event_details,:photo)

  end
  protected
  def profile
    @account = current_account
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(program) do |f| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Event_Name %>
    <%= f.text_field :Event_Name %>
  </div>
    <div class="field">
      <%= f.label :Event_Details %>
      <%= f.text_area :event_details %>
    </div>
    <p>
      <%= f.file_field :photo %>
    </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/_in.html.erb
<style>
  .post_container {
  display: inline-block;
  }



</style>

<h1>Programs</h1>

  <section id="gallery" class="parallax section" style="background-image: url(http://themepush.com/demo/runcharity/assets/img/2.jpg);">
    <div class="wrapsection">
      <div class="parallax-overlay" style="background-color:#00c1c1;opacity:0.9;"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12 sol-sm-12">
            <div class="maintitle">
              <h3 class="section-title">Events Gallery</h3>
              <p class="lead wow flipInX" style="content: '\007C\00a0\00a0';">
                Have a look at your past events gallery, see how much fun we have while helping people all over the world. Join our community today!
              </p>
            </div>
          </div>
          <div class="col-md-11" style="content: '\007C\00a0\00a0';align-content: center">
  <%@programs = Program.all  %>
  <%i = 1  %>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="float: left">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <table>
              <thead><tr>
                <ul>
                  <div class="col-md-11">

  <% @programs.each do |program| %>
      <%i = 1  %>

                    <div id="myCarouselWrapper" class="container-fluid" style="align-content: center">

                      <div id="myCarousel" class="carousel slide">

                        <div class="carousel-inner" role="listbox">
                          <div class="item active">

                            &nbsp;&nbsp;&nbsp;&nbsp;
                    <th width="1cm" colspan="2"><td>
                <div class="post_container" style="height: 15cm;width: 8cm">
                  <!--<a href="https://ununsplash.imgix.net/photo-1429277158984-614d155e0017?fit=crop&amp;fm=jpg&amp;h=700&amp;q=75&amp;w=1050" title="">-->
                  <%= image_tag program.photo.url(:medium),style:"border: double;display: inline-block; width: 400.2px;height:200px" ,class:"image-responsive"%>
                  <!--<img src="https://ununsplash.imgix.net/photo-1429277158984-614d155e0017?fit=crop&amp;fm=jpg&amp;h=700&amp;q=75&amp;w=1050" alt="" class="image-responsive">-->
                  <div class="description" style="height: 3cm">
                    <b><%= link_to program.Event_Name, program,:id=> 'program.id',style:'background-color: white;height:0.7cm' %></b>
                    <span><i><b><%= link_to 'Donate', mdos_path,style:'background-color: white;height:0.7cm;float:right' %></b></i></span>
                    <span class="camera"><i class="fa fa-camera"></i></span>
                    <div class="clearfix"></div>
                  </div>
                </div>
                          </td>
                             </th> <!-- Controls -->




                          </div>

                        </div>

                      </div>
                    </div>
                    &nbsp;&nbsp;&nbsp;
<% end %>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="float: right">
                      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="float: right"></span>
                      <span class="sr-only">Next</span>
                    </a>
      </div>
                </ul></tr></thead>
            </table> </div>

        </div>
      </div>
    </div>
 </section>
<br>
<% if user_signed_in?  %><%= button_to( "Add New Event", new_program_path, :method => :get )%><% end %>

<% if user_signed_in? && current_user.email == 'st118173@ait.asia' %><%= button_to( "Users Profile", usersinfo_userlist_path, :method => :get )%><%end%>
<% if user_signed_in? && current_user.email != 'st118173@ait.asia' %><%= button_to( "Users list", usersinfo_userlist_path, :method => :get )%><%end%>


         <!--.container-->
<script>
  $('#myCarousel').carousel({
    interval: 4000
  });

  $('.carousel .item').each(function(){
    var next = $(this).next();
    if (!next.length) {
      next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));

    for (var i=0;i<2;i++) {
      next=next.next();
      if (!next.length) {
        next = $(this).siblings(':first');
      }

      next.children(':first-child').clone().appendTo($(this));
    }
  });
</script>
<style>

</style>

app/views/programs/_sho.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= Program.Event_Name %>
</p>
<p>
  <strong>Event Details:</strong>
  <%= @program.event_details %>
</p>

<h3>Comments</h3>

<%= render @program.comts %>





<p><%= render 'comts/form' %></p>

<%= button_to( "Donate", new_reg_path, :method => :get, :class => 'btn btn-primary' )%>
<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<% if user_signed_in? && current_user.role==nil %>
<h1>Please Proceed to Pay to get access to webiste</h1>
    <script type="text/javascript">
      window.location.href="/regs/new"  // put your correct path in a string here
    </script>

<% else %>


<!--<h3 align="center"><font color="#a52a2a"> <%= link_to 'Click here to latest Database Dump', '/maa/dump_dir1/Arunlog1.text',{:style => 'color:darkgreen;'} %></font>-->
<!--</h3>-->

<h1>Programs</h1>

<table class = "table table-hover">
  <thead>
  <tr>
    <th>Event name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @programs.each do |program| %>
      <tr>
        <% @sho = program.id %>
        <td><%= program.Event_Name %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= button_to( "Donate", new_mdo_path, :method => :get )%></td>

        <% if user_signed_in? %> <td><%= link_to 'Edit', edit_program_path(program) %></td><% end %>
        <% if user_signed_in? && current_user.email == 'st118173@ait.asia' %> <td><%= link_to 'Delete Event', program, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in?  %><%= button_to( "Add New Event", new_program_path, :method => :get )%><% end %>

<% if user_signed_in? && current_user.email == 'st118173@ait.asia' %><%= button_to( "Users Profile", usersinfo_userlist_path, :method => :get )%><%end%>
<% if user_signed_in? && current_user.email != 'st118173@ait.asia' %><%= button_to( "Users list", usersinfo_userlist_path, :method => :get )%><%end%>
<% end %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @program.Event_Name %>
</p>
<p>
  <strong>Event Details:</strong>
  <%= @program.event_details %>
</p>
<%= image_tag @program.photo.url(:medium) %>
<h3>Comments</h3>

<%= render @program.comts %>





<p><%= render 'comts/form' %></p>

<%= button_to( "Donate", new_reg_path, :method => :get, :class => 'btn btn-primary' )%>
<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>