config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout "application"
  before_action :set_course, only: [:show, :edit, :update, :destroy, :upload, :do_upload, :resume_upload, :update_status, :reset_upload]
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil
      redirect_to new_reg_path

    end
  end
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.order(name: :asc)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    # If upload is not commenced or finished, redirect to upload page
    return redirect_to upload_course_path(@course) if @course.status.in?(%w(new uploading))
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit

  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.status = 'new'

    respond_to do |format|
      if @course.save
        format.html { redirect_to upload_course_path(@course), notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @course.assign_attributes(status: 'new', upload: nil) if params[:delete_upload] == 'yes'

    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Materila was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /courses/:id/upload
  def upload

  end

  # PATCH /courses/:id/upload.json
  def do_upload
    unpersisted_course = Course.new(upload_params)

    # If no file has been uploaded or the uploaded file has a different filename,
    # do a new upload from scratch
    if @course.upload_file_name != unpersisted_course.upload_file_name
      @course.assign_attributes(upload_params)
      @course.status = 'uploading'
      @course.save!
      render json: @course.to_jq_upload and return

      # If the already uploaded file has the same filename, try to resume
    else
      current_size = @course.upload_file_size
      content_range = request.headers['25000']
      begin_of_chunk = content_range[/\ (.*?)-/,1].to_i # "bytes 100-999999/1973660678" will return '100'

      # If the there is a mismatch between the size of the incomplete upload and the content-range in the
      # headers, then it's the wrong chunk!
      # In this case, start the upload from scratch
      unless begin_of_chunk == current_size
        @course.update!(upload_params)
        render json: @course.to_jq_upload and return
      end

      # Add the following chunk to the incomplete upload
      File.open(@course.upload.path, "ab") { |f| f.write(upload_params[:upload].read) }

      # Update the upload_file_size attribute
      @course.upload_file_size = @course.upload_file_size.nil? ? unpersisted_course.upload_file_size : @course.upload_file_size + unpersisted_course.upload_file_size
      @course.save!

      render json: @course.to_jq_upload and return
    end
  end

  # GET /courses/:id/reset_upload
  def reset_upload
    # Allow users to delete uploads only if they are incomplete
    raise StandardError, "Action not allowed" unless @course.status == 'uploading'
    @course.update!(status: 'new', upload: nil)
    redirect_to @course, notice: "Upload reset successfully. You can now start over"
  end

  # GET /courses/:id/resume_upload.json
  def resume_upload
    render json: { file: { name: @course.upload.url(:default, timestamp: false), size: @course.upload_file_size } } and return
  end

  # PATCH /courses/:id/update_upload_status
  def update_status
    raise ArgumentError, "Wrong status provided " + params[:status] unless @course.status == 'uploading' && params[:status] == 'uploaded'
    @course.update!(status: params[:status])
    head :ok
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:name,:details)
  end

  def upload_params
    params.require(:course).permit(:upload)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_file.html.erb
<td><%= button_to 'Donate Amount', new_mdo_path,:method => :get,class: "btn btn-large btn-success" %></td>
<td><%= button_to 'Donate Education materials', course_path,:method => :get,class: "btn btn-large btn-success" %></td>

app/views/courses/_form.html.erb
<%= form_for @course, html: { multipart: true, id: "fileupload" } do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:" %>
          </h2>
          <ul>
            <% @course.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="col-md-5">
      <div class="row">
        <h3>
          Material name
        </h3>
        <div class="padding-left">
          <%= f.text_field :name %>
        </div>
        <h3>
          Material details
        </h3>
        <div class="padding-left">
          <%= f.text_area :details %>
        </div>
      </div>
      <% if @course.upload_done? %>
          <div class="row">
            <h3>
              Uploaded material
            </h3>
            <div class="padding-left">
              <div class="row">
                <%= @course.upload_file_name + " (" + number_to_human_size(@course.upload_file_size.to_s) + ")" %>
              </div>
              <div class="row">
                <%= check_box_tag :delete_upload, 'yes', false %>
                <%= label_tag :delete_upload, 'delete this file', class: 'text-danger' %>
              </div>
            </div>
          </div>
      <% end %>
      <div class="empty-space"></div>
      <div class="row">
        <% submit_text = controller_name == 'new' ? "Create" : "Save" %>
        <%= f.submit submit_text, class: "btn btn-success" %>
      </div>
    </div>
<% end %>

app/views/courses/edit.html.erb
<h1 class="co">Editing material uploaded</h1>
<table>
  <%= button_to 'Show', @course,class: "btn btn-success" ,:method => :get %>
  &nbsp;&nbsp;
  <%= button_to 'Back', courses_path,class: "btn btn-success" ,:method => :get %>
</table>
<%= render 'form' %>

<br><br><br><br><br><br><br><br>
<script>
  $(document).ready(function(){

    $('html, body').animate({

      scrollTop: $(".co").offset().top

    },1000);

  });
</script>

app/views/courses/file.html.erb
<td><%= button_to 'Donate Amount', new_mdo_path,:method => :get,class: "btn btn-large btn-success" %></td>
<td><%= button_to 'Donate Education materials', course_path,:method => :get,class: "btn btn-large btn-success" %></td>

app/views/courses/index.html.erb
<h1>
  Education materials
  <%= button_to 'Upload material', new_course_path,:method => :get,class: "btn btn-large btn-success" %>
</h1>
<hr/>

<h3 align="center">

<div id="stream" style="width: 24cm">


      <div id="stream-list" class="follow-list" >
<ul>
  <table > <tr align="">Material Name</tr>

          <% @courses.each do |course| %>
        <ul>
        <label for="course<%= course.id %>" >
                <li id="stream_item">
                  <table>
                    <td><%= course.name %></td>
                   <td><%= button_to 'View', course,:method => :get,class: "btn btn-large btn-success" %></td>
                  </table>
                </li>
              </label>
              </ul>
          <% end %>
  </table>
        </ul>

      </div>
</div>

</h3>

app/views/courses/new.html.erb
<h1>New material donation</h1>
<hr/>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1>
  File Name: <%= @course.name %>
  <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-pencil"), edit_course_path(@course) %>
or
  <%= link_to 'Back', '/courses' %>
</h1>
<hr/>
<div class="empty-space"></div>
<h3>
  Material details
</h3>
<div class="padding-left">
  <div class="row">
    <%= @course.details %>
  </div>

</div>
<h3>
  Uploaded Material
</h3>
<div class="padding-left">
  <div class="row">
    <%= @course.upload_file_name + " (" + number_to_human_size(@course.upload_file_size.to_s) + ")" %>
  </div>
  <div class="row">
    <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-download") + " Download", @course.upload.url, class: "btn btn-lg btn-success" %>
  </div>
</div>

app/views/courses/upload.html.haml
%h1
  Please Upload file here
%hr

= form_for @course, url: upload_course_path, method: :post, html: { multipart: true, id: "fileupload" } do |f|
  .row
    %h3
      Please Select a file of type zip / pdf*
    .padding-left
      = @course.name
  
  .row.empty-space

  .row 
    - unless @course.status == 'uploading'
      .alert.alert-success.smaller-text
        To begin an upload, please first select a file from your computer.
    - else
      .alert.alert-warning.smaller-text
        The system detected an unfinished upload. To resume it, please select the same file and press the green button. <br />
        Resume not working or receiving error messages? Then please click #{link_to 'here', reset_upload_course_path(@course)} to delete the temoporary file and start over.

  .row.fileupload-buttonbar
    #js-data{ data: { course: @course.id } }
    .col-lg-7
      .btn.btn-primary.fileinput-button
        %i.glyphicon.glyphicon-plus
        Select a file
        = f.file_field :upload

  %table.table.table-striped#js-file-container{ role: "presentation" }
    %tbody.files

:javascript
  $(document).ready(function () {
    var course_id = $('#js-data').data('course');
    var controller_name = $('body').data('controller');
    var model_instance_path = '/' + controller_name + '/' + course_id;
    var resume_path = model_instance_path + '/resume_upload';
    var update_status_path = model_instance_path + '/update_status';

    $('#fileupload').fileupload({
      maxNumberOfFiles: 1,
      maxChunkSize: 10000000, // 10 MB
      type: 'PATCH',
      add: function (e, data) {
        var that = this;
        $.getJSON(resume_path, { file: data.files[0].name }, function (result) {
            var file = result.file;
            data.uploadedBytes = file && file.size;
            $.blueimp.fileupload.prototype
                .options.add.call(that, e, data);
        });
      }
    });

    $('#fileupload')
      .bind('fileuploadchunkdone', function (e, data) {
        var perc = parseInt(data.loaded / data.total * 100, 10);
        $('#js-completed').html(perc + "%");
      })
      .bind('fileuploaddone', function (e, data) {
        $.ajax({
          url: update_status_path,
          type: "PATCH",
          data: { status: 'uploaded'},
          success: function(data) {
            window.location.replace(model_instance_path);
          } 
        });
      });
    });

:plain
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-upload fade">

            <td width="45%">
                <p class="name"><h3>{%=file.name%}</h3></p>
                <p class="size">Processing...</p>
                <strong class="error text-danger"></strong>

                {% if (!i && !o.options.autoUpload) { %}
                    <button class="btn btn-success start" disabled>
                        <i class="glyphicon glyphicon-upload"></i>
                        Start / resume
                    </button> 
                {% } %}
                {% if (!i) { %}
                    <button class="btn btn-danger cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        Cancel upload
                    </button>
                {% } %}
            </td>
            <td width="45%" style="vertical-align: middle;">
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                <p><h1 id="js-completed" align="center"></h1></p>
            </td>
        </tr>
    {% } %}
  </script>

  <script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade">
            <td>
                <span class="preview">
                    {% if (file.thumbnailUrl) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                    {% } %}
                </span>
            </td>
            <td>
                <p class="name">
                    {% if (file.url) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                    {% } else { %}
                        <span>{%=file.name%}</span>
                    {% } %}
                </p>
                {% if (file.error) { %}
                    <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                {% } %}
            </td>
            <td>
                <span class="size">{%=o.formatFileSize(file.size)%}</span>
            </td>
            <td>
                {% if (file.deleteUrl) { %}
                    <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Delete</span>
                    </button>
                    <input type="checkbox" name="delete" value="1" class="toggle">
                {% } else { %}
                    <button class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancel</span>
                    </button>
                {% } %}
            </td>
        </tr>
      {% } %}
    </script>