config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/maa_addresses_controller.rb
class MaaAddressesController < ApplicationController
  before_action :set_maa_address, only: [:show, :edit, :update, :destroy]
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil
      redirect_to new_reg_path

    end
  end
  # GET /maa_addresses
  # GET /maa_addresses.json
  def index
    @maa_addresses = MaaAddress.all
  end

  # GET /maa_addresses/1
  # GET /maa_addresses/1.json
  def show
  end

  # GET /maa_addresses/new
  def new
    @maa_address = MaaAddress.new
  end

  # GET /maa_addresses/1/edit
  def edit
  end

  # POST /maa_addresses
  # POST /maa_addresses.json
  def create
    @maa_address = MaaAddress.new(maa_address_params)

    respond_to do |format|
      if @maa_address.save
        format.html { redirect_to @maa_address, notice: 'Maa address was successfully created.' }
        format.json { render :show, status: :created, location: @maa_address }
      else
        format.html { render :new }
        format.json { render json: @maa_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maa_addresses/1
  # PATCH/PUT /maa_addresses/1.json
  def update
    respond_to do |format|
      if @maa_address.update(maa_address_params)
        format.html { redirect_to @maa_address, notice: 'Maa address was successfully updated.' }
        format.json { render :show, status: :ok, location: @maa_address }
      else
        format.html { render :edit }
        format.json { render json: @maa_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maa_addresses/1
  # DELETE /maa_addresses/1.json
  def destroy
    @maa_address.destroy
    respond_to do |format|
      format.html { redirect_to maa_addresses_url, notice: 'Maa address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maa_address
      @maa_address = MaaAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maa_address_params
      params.require(:maa_address).permit(:postal_address)
    end
end

app/helpers/maa_addresses_helper.rb
module MaaAddressesHelper
end

app/views/maa_addresses/_form.html.erb
<%= form_for(maa_address) do |f| %>
  <% if maa_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maa_address.errors.count, "error") %> prohibited this maa_address from being saved:</h2>

      <ul>
      <% maa_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :postal_address %>
    <%= f.text_area :postal_address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maa_addresses/edit.html.erb
<h1>Editing Maa Address</h1>

<%= render 'form', maa_address: @maa_address %>

<%= link_to 'Show', @maa_address %> |
<%= link_to 'Back', maa_addresses_path %>

app/views/maa_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maa Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Postal address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maa_addresses.each do |maa_address| %>
      <tr>
        <td><%= maa_address.postal_address %></td>
        <td><%= link_to 'Show', maa_address %></td>
        <td><%= link_to 'Edit', edit_maa_address_path(maa_address) %></td>
        <td><%= link_to 'Destroy', maa_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maa Address', new_maa_address_path %>

app/views/maa_addresses/new.html.erb
<h1>New Maa Address</h1>

<%= render 'form', maa_address: @maa_address %>

<%= link_to 'Back', maa_addresses_path %>

app/views/maa_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Postal address:</strong>
  <%= @maa_address.postal_address %>
</p>

<%= link_to 'Edit', edit_maa_address_path(@maa_address) %> |
<%= link_to 'Back', maa_addresses_path %>